[package]
name = "crab-shell"
version = "0.1.0"
edition = "2024"

[features]
parallel = ["rayon"]

[dependencies]
glob = "0.3"
rayon = { version = "1", optional = true }

[dev-dependencies]
tempfile = "3"
